import { Event } from '@/types/event';

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-001',
    title: 'Economics Case Competition',
    description:
      'Compete in teams of 4 to analyze a real-world economic policy challenge. Cash prizes for top 3 teams. Open to all faculties; economics knowledge is helpful but not required.',
    date: '2026-05-10',
    time: '10:00 AM',
    location: 'Chan Centre for the Performing Arts, UBC Vancouver',
    capacity: 80,
    registeredCount: 62,
    isPaid: false,
    price: null,
    imageUrl: null,
    category: 'Competition',
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'evt-002',
    title: 'Networking Night with TD Economics',
    description:
      'Meet economists and analysts from TD Bank. Bring your resume. Light refreshments provided. Dress business casual. Limited spots, so register early.',
    date: '2026-05-17',
    time: '6:00 PM',
    location: 'TD Tower, 700 W Georgia St, Vancouver',
    capacity: 40,
    registeredCount: 38,
    isPaid: false,
    price: null,
    imageUrl: null,
    category: 'Networking',
    createdAt: '2026-04-02T00:00:00Z',
  },
  {
    id: 'evt-003',
    title: 'Annual VSEUS Gala',
    description:
      'Our flagship year-end gala celebrating student achievement in economics. Formal dinner, awards ceremony, and keynote speaker. Ticket price covers venue and catering.',
    date: '2026-05-30',
    time: '7:00 PM',
    location: 'Fairmont Hotel Vancouver, 900 W Georgia St, Vancouver',
    capacity: 120,
    registeredCount: 45,
    isPaid: true,
    price: 35,
    imageUrl: null,
    category: 'Social',
    createdAt: '2026-04-03T00:00:00Z',
  },
  {
    id: 'evt-004',
    title: 'Research Skills Workshop',
    description:
      'A hands-on workshop covering economic research methodology, data sources (FRED, Statistics Canada, World Bank), and how to structure a policy brief. Certificates provided.',
    date: '2026-06-05',
    time: '2:00 PM',
    location: 'Buchanan Tower 1197, UBC Vancouver',
    capacity: null,
    registeredCount: 29,
    isPaid: false,
    price: null,
    imageUrl: null,
    category: 'Workshop',
    createdAt: '2026-04-04T00:00:00Z',
  },
  {
    id: 'evt-005',
    title: 'Summer Economics Symposium',
    description:
      'A half-day symposium featuring student paper presentations, faculty discussants, and a panel on careers in economics. Submit your paper by May 20th to present.',
    date: '2026-06-15',
    time: '9:00 AM',
    location: 'Life Sciences Centre, UBC Vancouver',
    capacity: 200,
    registeredCount: 88,
    isPaid: false,
    price: null,
    imageUrl: null,
    category: 'Academic',
    createdAt: '2026-04-05T00:00:00Z',
  },
];

export const ADMIN_USER = {
  id: 'admin-001',
  email: 'admin@vseus.ca',
  password: 'admin123',
  name: 'VSEUS Admin',
  studentId: '000000000',
  role: 'admin' as const,
};
